### ISSUE TITLE
[Subscriber] Update Topic dynamically

### ISSUE THREAD

**Issue by Alby407** [ltiseni94/rosreact#5]
It would be nice to update the Subscriber if the topic changes dynamically. Right now, if I manage the topic via useState, the Subscriber does not update the topic.

**Comment by ahoenerBE** [comment]
Hi @Alby407 
You actually can do this, here's an example I wrote with `useSubscription` and a checkbox
```ts
type Int32 = {
    data: number;
}

type ExampleProps = {
    topicProps: UseSubscriptionProps<Int32>;
}

const countTopicProps: UseSubscriptionProps<Int32> = {
    topic: "/rosbridgetest/count",
    messageType: "std_msgs/Int32",
}

const doubleCountTopicProps: UseSubscriptionProps<Int32> = {
    topic: "/rosbridgetest/doublecount",
    messageType: "std_msgs/Int32",
}

const Example: React.FC<ExampleProps> = ({topicProps}) => {
    const message = useSubscription(topicProps);
    return <div>{message?.data}</div>;
};

function App() {

    const [topicProps, setTopicProps] = useState(countTopicProps);

    const changeTopic = (state: boolean) => {
        if(state) {
            setTopicProps(doubleCountTopicProps);
        }
        else {
            setTopicProps(countTopicProps);
        }
    }

    return (
        <RosConnection url={url} autoConnect>
            <label>
                Use Double Count
                <input type={"checkbox"} defaultChecked={false} onChange={e => changeTopic(e.target.checked)} />
            </label>
            <Example topicProps={topicProps}/>
        </RosConnection>
    )
}

```

In my backend I have 2 publishers, one on `/rosbridgetest/count`, and one on `/rosbridgetest/doublecount` which just publishes double the number that count does. If I click the checkbox, it'll update the props that useSubscription uses, and it'll change data sources. Note that both topics are Int32 because I assume the `data` field. You'll have to write some typings for your components and add some props if you want to accept anything

**Comment by drewhoener** [comment]
Hi @Alby407 
I've created a repo over on my personal account to showcase some examples of how to dynamically change these things. It includes a more fleshed out example showing how to do the thing you want.  
I'll work on creating more complete examples at some point but I don't have the time atm. I hope these will help.  
https://github.com/drewhoener/rosreact-examples/
