### ISSUE TITLE
Minimal Example for useSubscription

### ISSUE THREAD

**Issue by Alby407** [ltiseni94/rosreact#6]
Hey!

To me, it is not clear how to use the `useSubscription` hook. I tried the example from PR #2, but it does not seem to work, I don't get any messages.
Is it possible to provide a minimal example in the README?

Here my code:

```
const Example = () => {
  const message = useSubscription({
    topic: "/client_count",
    messageType: "std_msgs/Int32",
    customCallback: (msg) => console.log(msg),
  });
  return <div>{message}</div>;
};
```
When I log `message`, I get `null`. It seems the hook does nothing.

**Comment by Alby407** [comment]
I downgraded from version 0.4 to 0.3. Now the hook works as expected. It seems there is a problem in version 0.4

**Comment by drewhoener** [comment]
Hi @Alby407 
Your thinking is right on in your implementation. My only advice is that having your custom callback non-memoized can cause an infinite loop of updates. I would recommend moving your params outside your component (since they probably don't need to be inside anyway), or wrapping your console.log function in a useCallback.

```ts
/** Option 1 **/
const topicProps: UseSubscriptionProps<Int32> = {
    topic: "/rosbridgetest/count",
    messageType: "std_msgs/Int32",
    customCallback: msg => console.log(msg),
}

const Example = () => {
    const message = useSubscription<Int32>(topicProps);
    return <div>{message?.data}</div>;
};

/** Option 2 **/
const Example = () => {
    const messageCb = useCallback((msg: Int32) => console.log(msg), []);
    const message = useSubscription<Int32>({
        topic: "/rosbridgetest/count",
        messageType: "std_msgs/Int32",
        customCallback: messageCb,
    });
    return <div>{message?.data}</div>;
};
```

Also, I had an issue using /client_count as my topic, RosBridge complained there was a QOS mismatch so I made my own topic.

You're also right in that I introduced a bug by mistake. The RosConnection component keeps a ref of the Ros object to use in the provider. By default, this ref is an empty ros object. Because of the order of useEffect call (child -> parent), this results in the child using a ros connection that is then immediately unused when the parent updates.
I didn't notice this because my default testing environment initializes a store, preventing the application content from updating until it's finished.
```ts
let initialized = false;

function App() {
  const [ready, setReady] = useState(false);

  const startApp = useCallback(async () => {
    if (initialized) {
      return;
    }
    try {
      // Do anything that has to be done on first app run
      setReady(true);
      initialized = true;
    } catch (e) {
      console.log('Failed to start the app');
      console.error(e);
    }
  }, []);

  useEffect(() => {
    startApp().then(() => console.log('App Started'));
  }, [startApp]);

  return (
    <ThemeProvider theme={mainTheme}>
      <>
        <GlobalStyle />
        <StoresProvider>
          <ServicesProvider>
            <RosConnection url={import.meta.env.VITE_ROS_BRIDGE_URL} autoConnect>
              {ready && <AppContent />}
            </RosConnection>
          </ServicesProvider>
        </StoresProvider>
      </>
    </ThemeProvider>
  );
}

export default App;
```
So the RosConnection would always finish init before children. 
This isn't intended behavior, I'll have a PR for this fix in ASAP.
Thanks for noticing :)
